name: Check Lint, Tests and Build
on:
  pull_request:
    branches: [main, feature/*, fix/*]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@aws'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run Unit and E2E tests
        run: npm run tests:unit && npm run tests:e2e
      - name: Run Lint
        run: npm run lint
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-snapshots
          path: ./ui-tests/__test__/__image_snapshots__
          retention-days: 30