name: Publish Release
on:
  push:
    tags: ['v*.*']

  workflow_dispatch:
jobs:
  # Build, Test and Check linting
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@aws'
      - run: npm ci
      - name: Check lint
        run: npm run lint
      - name: Build mynah-ui
        run: npm run build
      - name: Run tests
        run: npm test
  
  # Build and upload the demo app assets
  preparedemo:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build demo app
        run: npm run packdemo
      - name: Get release info
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload demo app to assets
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./example/mynah-ui-demo.zip
          asset_name: mynah-ui-demo.zip
          asset_content_type: application/zip
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
            source: ./example/dist
            destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      
  # Publish version to npm
  npmpublish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # Deploy to github pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: preparedemo
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Upload communication channels
  updatechannels:
    runs-on: ubuntu-latest
    needs: preparedemo
    steps:
      - name: Update Channels
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ secrets.SLACK_ENDPOINT }}'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"version": "${{ steps.get_release.outputs.tag_name }}", "url": "${{ steps.get_release.outputs.html_url }}"}'